workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    # integrations:
    #   app_store_connect: codemagic
    environment:
      flutter: '3.19.3'
      xcode: "15.4"
      cocoapods: default
    scripts:
      - name: clean and create
        script: |
          rm -r ios
          rm -r android
          rm -r macos
          rm -r linux
          rm -r web
          flutter create --org com.ensembleui --project-name khurrambuild --platform=ios .
      - name: Setup code signing identities
        script: |
          app-store-connect fetch-signing-files com.ensembleui.khurrambuild --create --type IOS_APP_STORE --platform IOS
          keychain initialize
          keychain add-certificates
      - name: Installing dependencies
        script: |
          flutter packages pub get
      - name: Building ios
        script: |
          xcode-project use-profiles
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist --no-tree-shake-icons --build-name=1.0.0 --build-number=20

      - name: Publishing
        script: |
          app-store-connect publish --path /Users/builder/clone/build/ios/ipa/khurrambuild.ipa
    artifacts:
      - /build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log



